stages:

  - build:
  - test:
  - push_to_dockerhub:
  - deploy: 

build_jobs:
  stage: build  
  scripts:
    - docker build -t node-app:latest .
  tags:
    - dev

test_jobs:
  stage:  test
  scripts:
    - echo "Testing...."
  tags:
    - dev
push_jobs:
  stage:  push_to_dockerhub
  scripts:
    - docker login -u $DOCKERHUB_USER -p$DOCKERHUB_PASSWORD
    - docker image tag node-app:latest $DOCKERHUB_USER/node-app:latest
    - docker push $DOCKERHUB_USER/node-app:latest
  tags:
    - dev
stage_job:
  stage:  deploy
  scripts:
    - docker-compose up -d
  tags:
    - dev
